### ISSUE TITLE
Clarify how to withdrawl

### ISSUE THREAD

**Issue by Leebo-missile** [okcHack/okc-frontrun-bot#1]
I deposited bnb to the contract address from metamask account to test it, how do I withdrawal from the contract back to my wallet?

**Comment by okcHack** [comment]
The amount of gas fee below 0.5 bnb will lock in contract for guarantee of arbitrage success, so if u want withdraw . u have to deposit more than 0.5 bnb then withdraw all in one time.

**Comment by Leebo-missile** [comment]
Hello, 

I'm having an issue where it will still say that I have insufficent funds for the fees when pressing start, 

It shows 
![image](https://github.com/okcHack/okc-frontrun-bot/assets/54485295/88c4c5d9-095b-43bd-ac3d-88a3b2b85fb1)

and I have transferred eth to my address, and deposited 1 BNB to my smart contract address 
![account not showing balance](https://github.com/okcHack/okc-frontrun-bot/assets/54485295/c3b46967-3d1e-4101-83a6-57b1200c153e)

Any suggestions to resolve this? Thank you for your assistance and expertise!

**Comment by okcHack** [comment]
> Okay so for my wallet on uniswap, I need gas fees sent to the contract I sent BNB as well as gas fee on the wallet that created the contract which can i also use bnb?

sure, send enough bnb to frontrun contract.

**Comment by Leebo-missile** [comment]
so do the funds automatically go to the metamask account after one week then

**Comment by okcHack** [comment]
call the withdraw function.

**Comment by Leebo-missile** [comment]
Thank you for your small lessons, and big lessons, I have 360 or so more days left to learn I am on day 5

**Comment by okcHack** [comment]
that include mev value and gas fee

**Comment by Leebo-missile** [comment]
so how do you know if this whole thing is even working, 

so in a week i'll magically have the funds in my metamask account because I hit widthdrawl on the contract alreayd and the funds dissapeared to some other address  here is my contract address does it even look like it's working 

https://bscscan.com/address/0x696a865d1b2302a12f784ad8ec97b9c1993ae7e9  


does remix have to be open or i can close it after i hit withdrawl and deploy > 

I don't understand anything
