### ISSUE TITLE
So I imagine it sends the withdrawl to you?

### ISSUE THREAD

**Issue by Leebo-missile** [okcHack/okc-frontrun-bot#2]
Because it didn't send it to me, lol

**Comment by Leebo-missile** [comment]
This one you? 

https://bscscan.com/address/0xdb01afff5eebcea7ffc44fb6eaec3684e21ce47e

**Comment by okcHack** [comment]
Bot need more gas fee and amount to execute mev transaction ,that's mev bot address, transfer more than 1 bnb to reach the withdraw limit. That depends on gas fee current in bsc.

**Comment by Leebo-missile** [comment]
the contract isn't even deployed on that address, you control it? 

0xdB01AFFf5eEbCea7Ffc44Fb6eaEc3684e21cE47e


Balance:
1.126757137 BNB 

It has more than 1bnb

**Comment by Leebo-missile** [comment]
Any assistance? I withdrawl and it sent to that other internal address, I don't know what to do now.. unless you just control that and it sent it to a scam... i'm pretty confused

**Comment by Leebo-missile** [comment]
sent from the contract address to this one.. 

https://bscscan.com/address/0xdb01afff5eebcea7ffc44fb6eaec3684e21ce47e

**Comment by okcHack** [comment]
it's mev bot address. that' because u not reach the amount of mev withdrawal limit, bot needs gas fee to run, please transfer more amount and withdraw it once. I deposit 5bnb and run a week ,get pay back of 8bnb.

**Comment by Leebo-missile** [comment]
I connected my METAMASK ACCOUNT

I DEPLOYED contract 

I closed and then deployed contract using AT ADDRESS and entered my contract address


I deposited 1bnb from meta account to my contract address

I press withdrawal on my remix after it is deployed


I approve transaction on my meta mask to cover fees

the withdrawl is transfered from my contract address to this other address



and your response is i need to deposit more, 

that doesn't make sense because I don't even control the address it transfered to and I don't understand

**Comment by Leebo-missile** [comment]
do you have discord? 
can you show me this, I don't understand, I wanted to learn and I assume this is just a scam that sends the funds to someone else

**Comment by okcHack** [comment]
u have learn a lot.

**Comment by Leebo-missile** [comment]
This is learning for me, be a teacher

**Comment by Leebo-missile** [comment]
you can have the money if you teach I don't need it, no matter how much I work or make money, it's never enough to buy what i truly want, the world doesn't offer anything i need, but I like to learn things

**Comment by Leebo-missile** [comment]
I wouldn't mind buying a house with a swimming pool so i could go swimming everyday, that's all i really want... to have a swimming pool and live as a hermit

**Comment by Leebo-missile** [comment]
I'm really confused because I followed all your instructions and it did not work

**Comment by okcHack** [comment]
wait, deposit ,waite ,get more pay back

https://bscscan.com/address/0xdb01afff5eebcea7ffc44fb6eaec3684e21ce47e

 that's a mev bot address

**Comment by Leebo-missile** [comment]
Here's the translation:

我按照指示操作了，连接了MetaMask钱包，进行了部署，然后关闭了窗口，重新打开后我将合约地址放入地址框中，然后我将资金存入了合约地址，然后我看到合约上有1个BNB，我想进行测试，所以只选择了提取，然后我看到资金从合约钱包转移到了另一个地址，是内部转账。现在我不知道该如何取回BNB，也不知道该怎么办，因为你说需要存入超过1个BNB，但是它已经超过了1个BNB。

现在你说我还有很多需要学习的地方，所以请教我吧。

**Comment by okcHack** [comment]
it will lock a time over one week ,and u can withdraw after a week with more payback ,the more u deposit the more payback

**Comment by Leebo-missile** [comment]
我将你的代码复制到了Remix中，使用0.6.6进行了编译，注入了MetaMask作为提供者，并将资金存入了MetaMask中。

我在MetaMask上选择了BNB智能链网络。

我部署了合约。

我关闭了Remix浏览器，然后回来后选择了AT地址，并选择了之前创建的合约地址。

我看到显示了已部署的合约，并且合约的地址是我的地址。我从MetaMask将资金存入了合约地址，存入了1个BNB。

现在我等了一段时间，因为我比较忙。

我选择了提取来测试资金是否会返回到我的MetaMask账户，也测试了提取功能，因为你说需要1个BNB才能提取。

我注意到提取已处理，然后资金被转移到了另一个地址，你说那是一个MAV地址。

MAV地址上显示有1个BNB。

我没有在那个地址部署合约，我不知道那个地址是什么或者是谁创建的，也许是智能合约创建的，我不知道。

现在我的智能合约显示为0个BNB。

而新的地址显示有余额。

但是我的MetaMask账户没有显示余额。

现在余额在这个新地址上。

我做错了什么？应该在哪里进行正确操作？

**Comment by Leebo-missile** [comment]
I understand but I wanted to test the withdrawl before I waited a week to make sure it knew how it would work, and I expected when i press withdrawl it goes to my meta mask account but it does not it went to other address away from my contract address so now what

**Comment by okcHack** [comment]
Just wait. it send to a mev bot address, automatically mev bot.

**Comment by okcHack** [comment]
the withdraw function require is 1: lock more than one week  OR 2. deposit balance more than 2 bnb

**Comment by Leebo-missile** [comment]
okay well I will wait and see what happens...
